<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find penguin_description)/urdf/base/base.transmission.xacro"/>
  <xacro:include filename="$(find penguin_description)/urdf/base/base.gazebo.xacro" />
  <xacro:include filename="$(find penguin_description)/urdf/sensors/asus_xtion_pro.urdf.xacro" />
  <xacro:include filename="$(find penguin_description)/urdf/sensors/hokuyo_utm30lx.urdf.xacro" />

  <!-- Properties -->
  <xacro:property name="GROUND_CLEARANCE" value="0.0403"/>
  <xacro:property name="width" value="0.20" />
  <xacro:property name="xpsvwhloffset" value="0.1405" />
  <xacro:property name="yactwhloffset" value="0.3" />
  <xacro:property name="bodylen" value="0.286" />
  <xacro:property name="wheel_w" value="0.039" />
  <xacro:property name="wheel_rad" value="0.075" />
  <xacro:property name="plat_rad" value="0.185" />
  <xacro:property name="plat_len" value="0.005" />
  <xacro:property name="HIGH_PLATFORM" value="0.286" />
  <xacro:property name="posz_laser" value="0.333" />
  <xacro:property name="posz_camera" value="1.059" />
  <xacro:property name="fwheel_rad" value="0.075" />
  <xacro:property name="pi" value="3.1415926535897931" />
  <xacro:property name="base_mass" value="30" />
  <xacro:property name="plat_mass" value="2" />
  <xacro:property name="actvwheel_mass" value="10" />
  <xacro:property name="psvwheel_mass" value="1" />
  <xacro:property name="M_PI" value="3.1415926535897931" />


  <!--left and right wheel-->
  <xacro:macro name="rl_wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_w}" radius="${wheel_rad}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_w}" radius="${wheel_rad}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.010" />
        <origin rpy="${pi/2} 0 0" xyz="0 0 0" />
        <inertia 
          ixx="${(1/12) * actvwheel_mass * (3 * wheel_rad * wheel_rad + wheel_w * wheel_w)}" ixy="0.0" ixz="0.0"
          iyy="${(1/12) * actvwheel_mass * (3 * wheel_rad * wheel_rad + wheel_w * wheel_w)}" iyz="0.0"
          izz="${0.5 * actvwheel_mass * wheel_rad * wheel_rad }" />
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <axis xyz="0 1 0"/>
	  <origin xyz="0 ${-yactwhloffset*reflect/2} ${-(bodylen/2)+GROUND_CLEARANCE+0.031}" rpy="0 0 0"/>
    </joint>
  
    <!-- extensions -->
    <xacro:penguin_rl_wheel_gazebo/>
    <xacro:penguin_wheel_transmission prefix="${prefix}"/>
  </xacro:macro>

  <!--front and back wheel-->
  <xacro:macro name="fb_wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_w}" radius="${fwheel_rad}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_w}" radius="${fwheel_rad}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.010" />
        <origin rpy="${pi/2} 0 0" xyz="0 0 0" />
        <inertia 
          ixx="${(1/12) * psvwheel_mass * (3 * fwheel_rad * fwheel_rad + wheel_w * wheel_w)}" ixy="0.0" ixz="0.0"
          iyy="${(1/12) * psvwheel_mass * (3 * fwheel_rad * fwheel_rad + wheel_w * wheel_w)}" iyz="0.0"
          izz="${0.5 * psvwheel_mass * fwheel_rad * fwheel_rad }" />
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <axis xyz="0 1 0"/>
	  <origin xyz="${xpsvwhloffset*reflect} 0 ${-(bodylen/2)+GROUND_CLEARANCE+0.031}" rpy="0 0 0"/>
    </joint>

    <!-- extensions -->
    <xacro:penguin_fb_wheel_gazebo/>
  </xacro:macro>

  <!-- Base -->
  <xacro:macro name="penguin_base">
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="White" />
      </visual>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${(bodylen/2)-GROUND_CLEARANCE-0.031+wheel_rad}" rpy="0 0 0" />
      <child link="base_link" />
      <parent link="base_footprint"/>
    </joint>

    <link name="base_link">
      <visual>
        <geometry>
           <cylinder length="${bodylen}" radius="${width}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 ${GROUND_CLEARANCE}"/>
        <material name="white"/>
      </visual>
      <collision>
        <geometry>
           <cylinder length="${bodylen}" radius="${width}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 ${GROUND_CLEARANCE}"/>
      </collision>
      <inertial>
        <mass value="${base_mass}" />
        <origin rpy="0 0 0" xyz="0 0 ${GROUND_CLEARANCE}" />
        <inertia 
          ixx="${(1/12) * base_mass * ( 3 * (0.1 * 0.1 + width * width) + bodylen)}" ixy="0.0" ixz="0.0"
          iyy="${(1/12) * base_mass * ( 3 * (0.1 * 0.1 + width * width) + bodylen)}" iyz="0.0"
          izz="${0.5 * base_mass * ( 0.1 * 0.1 + width * width)}" />
      </inertial>
    </link>

    <!-- wheel macros-->
    <xacro:rl_wheel prefix="right" reflect="1" />
    <xacro:rl_wheel prefix="left" reflect="-1" />
    <xacro:fb_wheel prefix="front" reflect="1"/>
    <xacro:fb_wheel prefix="back" reflect="-1"/>
  
    <!-- ASUS Xtion Pro -->
    <xacro:asus_xtion_pro name="camera" parent="base_link"/>

    <!-- Hokuyo utm30lx-->
    <xacro:hokuyo_utm30lx name="hokuyo" parent="base_link"/>

    <!-- extensions -->
    <xacro:penguin_fb_wheel_gazebo/>
  </xacro:macro>
</robot>

