# for controller spawner
ironfish_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ironfish_diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  right_wheel : 'rwheel_joint'
  left_wheel  : 'lwheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  enable_odom_tf: true

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3575 #0.178955289353836*2
  wheel_radius : 0.10 #0.10

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 0.96 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0  # m/s
      min_velocity           : -2.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.2  # m/s^2 #for teb
      min_acceleration       : -1.2 # m/s^2 #for teb
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0  # rad/s
      min_velocity           : -4.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 2  # rad/s^2
      min_acceleration       : -2  # rad/s^2
