# for controller spawner
ironfish_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ironfish_diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  right_wheel : 'rwheel_joint'
  left_wheel  : 'lwheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  enable_odom_tf: true

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.30
  wheel_radius : 0.1

  # Wheel separation and radius multipliers
  #wheel_separation_multiplier: 1.0 # default: 1.0
  #wheel_radius_multiplier    : 1.0 # default: 1.0
  wheel_separation_multiplier: 1.0 # default: 1.0 //See if under 3.14rad/s, it could rotate 1round/2sec
  wheel_radius_multiplier    : 1.0 # default: 1.0 //See if under 0.1m/s, it could travel 1m(1grid)/10sec

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -1.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2
      min_acceleration       : -0.5 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      min_velocity           : -2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # rad/s^2
      min_acceleration       : -0.8  # rad/s^2
